### ISSUE TITLE
3 required for Interpolation & Differentiation GUI.

### ISSUE THREAD

**Issue by MMDPROJECT** [MMDPROJECT/NumericalAnalysisMethods#21]
Please tell which libraries you do prefer to work with for implementing a GUI for interpolating methods.
@ranarokni @Grmamobin.

**Comment by ranarokni** [comment]
I prefer tkinter
But honestly don't know any other, so would be ok with anything else

**Comment by MMDPROJECT** [comment]
> I prefer tkinter
> But honestly don't know any other, so would be ok with anything else

As i have noticed **tkinter** is not that much flexible in terms of having enough widgets. Although working with it is really easy and we can get the work done very quickly.

I would prefer **flet** library of python. Which is actually quite similar to the **flutter** framework of the **dart**. We can easily design modern-looking pages with it's enormous widgets and features. Please have a look at the images in the this [link](https://flet.dev/gallery).

**Comment by Grmamobin** [comment]
> > I prefer tkinter
> > But honestly don't know any other, so would be ok with anything else
> 
> As i have noticed **tkinter** is not that much flexible in terms of having enough widgets. Although working with it is really easy and we can get the work done very quickly.
> 
> I would prefer **flet** library of python. Which is actually quite similar to the **flutter** framework of the **dart**. We can easily design modern-looking pages with it's enormous widgets and features. Please have a look at the images in the this [link](https://flet.dev/gallery).
> 

Well... I disagree with you guys !!
I'd rather use "PySide6" because it is very simple to use.

AND based on my limited experience with "flet" and "tkinter" I find that they are all time consuming to use....
